name: Shared Local Template
values:
  - key: baseUrl
    value: 'http://localhost:3000'
    enabled: true
  - key: authToken
    value: ''
    enabled: true
  - key: testUserId
    value: ''
    enabled: true
